import type { Metadata } from "next";
import { Noto_Serif_Bengali } from "next/font/google";
import "./globals.css";

const notoSerifBangla = Noto_Serif_Bengali({
  subsets: ["latin", "bengali"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" className={`${notoSerifBangla.className} h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        <div>navbar</div>
        {children}
        <div>footer</div>
      </body>
    </html>
  );
}
